name: Build a docker image and push to the registry

on: [workflow_dispatch]

env:
  IMAGE_NAME: runner
  IMAGE_TAG: v1

jobs:
  build:
    runs-on: debian-bullseye-slim
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f agent/Dockerfile
          docker push ${{ secrets.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}